### ISSUE TITLE
Add safe area for mobile.

### ISSUE THREAD

**Issue by itsarvinddev** [egortabula/side_sheet_material3#1]
[side_sheet_material3](https://github.com/egortabula/side_sheet_material3) overlaps the mobile status bar when used in a mobile app. As a result of the overlapping icon button not working.

![Screenshot_20230519-213341_server_mohesu](https://github.com/egortabula/side_sheet_material3/assets/59143934/7407073d-5212-4219-887a-5ea360a5a33a)

**Comment by egortabula** [comment]
Hello, it's done! Please update package in your dependencies to v. 0.0.2
